// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8bAmrfX6wj_CYWxJ4yXDSZGIJHfJcUoE',
    appId: '1:794293229990:web:bb0d69db41d889010d9767',
    messagingSenderId: '794293229990',
    projectId: 'hire-nest-4919d',
    authDomain: 'hire-nest-4919d.firebaseapp.com',
    storageBucket: 'hire-nest-4919d.firebasestorage.app',
    measurementId: 'G-4QKKZN5G13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4t9ti65nJIAjEbzp0FjD_dNFV4xGkYEs',
    appId: '1:794293229990:android:15a7b158b5cf8c850d9767',
    messagingSenderId: '794293229990',
    projectId: 'hire-nest-4919d',
    storageBucket: 'hire-nest-4919d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC40m0Pnrcco3ucKpyZ9RvFBtvKz9PO7co',
    appId: '1:794293229990:ios:3cf21502f250a74b0d9767',
    messagingSenderId: '794293229990',
    projectId: 'hire-nest-4919d',
    storageBucket: 'hire-nest-4919d.firebasestorage.app',
    iosBundleId: 'com.example.careerHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC40m0Pnrcco3ucKpyZ9RvFBtvKz9PO7co',
    appId: '1:794293229990:ios:3cf21502f250a74b0d9767',
    messagingSenderId: '794293229990',
    projectId: 'hire-nest-4919d',
    storageBucket: 'hire-nest-4919d.firebasestorage.app',
    iosBundleId: 'com.example.careerHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8bAmrfX6wj_CYWxJ4yXDSZGIJHfJcUoE',
    appId: '1:794293229990:web:29300832d5cde01b0d9767',
    messagingSenderId: '794293229990',
    projectId: 'hire-nest-4919d',
    authDomain: 'hire-nest-4919d.firebaseapp.com',
    storageBucket: 'hire-nest-4919d.firebasestorage.app',
    measurementId: 'G-QNX2RLCXJP',
  );
}
